#!/bin/bash
# Compile script for the FLUKE developers

#NOTE: This script requires files outside of the repository!!!

#Print FLUKE title
echo ""
echo "###################################################"
echo "#                                                 #"
echo "# FLUKE: Fields Layered Under Kohn-Sham Electrons #"
echo "#                                                 #"
echo "###################################################"
echo ""

### Compile non-dev FLUKE (compile-time error checking) ###
echo "Compiling the FLUKE binary..."
cd src/
g++ -fopenmp -static -O3 FLUKE.cpp -o FLUKE -I/usr/include/eigen3/
cd ../
rm src/FLUKE
echo ""

### Compile FLUKE development binary for test calculations ###
echo "Compiling the FLUKE development binary..."
cd src/
g++ -DDEVCOMP -fopenmp -g -static -O3 FLUKE.cpp -o FLUKE -I/usr/include/eigen3/
cd ../
mv src/FLUKE .
echo ""

### Compile FLUKE manual ###
echo "Compiling the documentation..."
cd src/
#Overkill to make sure all of the numbering is correct
pdflatex manual > doclog.txt
bibtex manual > doclog.txt
pdflatex manual > doclog.txt
pdflatex manual > doclog.txt
pdflatex manual > doclog.txt
pdflatex manual > doclog.txt
bibtex manual > doclog.txt
pdflatex manual > doclog.txt
pdflatex manual > doclog.txt
pdflatex manual > doclog.txt
#Remove junk files
rm -f manual.aux manual.bbl manual.lof doclog.txt manual.blg
rm -f manual.lot manual.out manual.toc manual.log
mv manual.pdf ../doc/FLUKE_manual.pdf
cd ../
echo ""

### Print code stats ###
echo "Number of FLUKE source code files:"
ls -al ./src/* | wc -l
echo "Total length of FLUKE (lines):"
cat ./src/* | wc -l
echo ""

### Finish ###
echo "Done."
echo ""
