#!/bin/bash

#A simple script to produce a constantly updating queue t.o.p.

#Usage: Qtop -q [ queue name ]
#Usage: Qtop -u [ username ]
#Usage: Qtop -r [ username ]

#Help mode
if [[ "$1" == *"-h"* ]]; then
  echo ""
  echo "A simple script to produce a constantly updating queue t.o.p."
  echo ""
  echo "Usage: Qtop -q [ queue name ]"
  echo "Usage: Qtop -r [ username ]"
  echo "Usage: Qtop -u [ username ]"
  echo "Usage: Qtop -u me"
  echo ""
  echo ""
  echo "  -q  Show active and queued jobs for a queue"
  echo ""
  echo "  -u  Show active and queued jobs for a user. Jobs for the"
  echo "      current user can be shown with the '-u me' command."
  echo ""
  echo "  -r  Show only active jobs for a user."
  echo ""
  echo "The script runs until the user presses 'q'"
  echo ""
  echo "Note: Behavior when refreshing the screen is terminal dependent."
  echo ""
  exit
fi

#User mode
if [[ "$1" == *"-u"* ]]; then
  export QtopUser=$2
  if [[ $2 == "me" ]]; then
    export QtopUser=$(whoami)
  fi 
  #Infinite loop, escape with Ctrl-C
  keypress=""
  while [ 0 -lt 1 ]
  do
    #Clear the screen
    #NB: 3 different types are included since the commands are
    # terminal dependent
    clear
    reset
    echo -en "\e[3J"
    #Print title  
    echo ""
    echo "Active and queued jobs for user ${QtopUser}:"
    #Print qstat titles that are lost in grep/sed
    echo "                                                      Req'd  Req'd   Elap"
    echo "Job ID    Username Queue    Jobname    SessID NDS TSK Memory Time  S Time"
    echo "--------- -------- -------- ---------- ------ --- --- ------ ----- - -----"
    #Find and replace usernames
    qstat -u ${QtopUser} | grep -e "${QtopUser}" \
    | sed 's/ft0805/Kratz /g' \
    | sed 's/fc1875/Hedi  /g' \
    | sed 's/ee4522/Andres/g' \
    | sed 's/fg3012/Alice /g' \
    | sed 's/fj9636/Tu    /g' \
    | sed 's/ej0271 /Sajeewa/g' \
    | sed 's/es4448/Pavel /g' \
    | sed 's/\.vpbs1//g'
    #Wait for 30 seconds before looping
    sleep 2.0
    for i in {1..15}
    do
      sleep 1.0
      read -t 1 -n 1 keypress
      if [[ "${keypress}" == *"q"* ]]; then
        echo ""
        exit
      fi
    done
  done
fi

#Running mode
if [[ "$1" == *"-r"* ]]; then
  export QtopUser=$2
  if [[ $2 == "me" ]]; then
    export QtopUser=$(whoami)
  fi
  #Infinite loop, escape with Ctrl-C
  keypress=""
  while [ 0 -lt 1 ]
  do
    #Clear the screen
    #NB: 3 different types are included since the commands are
    # terminal dependent
    clear
    reset
    echo -en "\e[3J"
    #Print title
    echo ""
    echo "Active jobs for user ${QtopUser}:"
    #Print qstat titles that are lost in grep/sed
    echo "                                                      Req'd  Req'd   Elap"
    echo "Job ID    Username Queue    Jobname    SessID NDS TSK Memory Time  S Time"
    echo "--------- -------- -------- ---------- ------ --- --- ------ ----- - -----"
    #Find and replace usernames of running jobs
    qstat -u ${QtopUser} | grep -e "${QtopUser}" \
    | grep -e " R " \
    | sed 's/ft0805/Kratz /g' \
    | sed 's/fc1875/Hedi  /g' \
    | sed 's/ee4522/Andres/g' \
    | sed 's/fg3012/Alice /g' \
    | sed 's/fj9636/Tu    /g' \
    | sed 's/ej0271 /Sajeewa/g' \
    | sed 's/es4448/Pavel /g' \
    | sed 's/\.vpbs1//g'
    #Wait for 30 seconds before looping
    sleep 2.0
    for i in {1..15}
    do
      sleep 1.0
      read -t 1 -n 1 keypress
      if [[ "${keypress}" == *"q"* ]]; then
        echo ""
        exit
      fi
    done
  done
fi

#Queue mode
if [[ "$1" == *"-q"* ]]; then
  #Infinite loop, escape with Ctrl-C
  keypress=""
  while [ 0 -lt 1 ]
  do
    #Clear the screen
    #NB: 3 different types are included since the commands are
    # terminal dependent
    clear
    reset
    echo -en "\e[3J"
    #Print basic info
    echo ""
    qstat -Q $2
    echo ""
    echo "Active and queued jobs on ${2}:"
    #Print qstat titles that are lost in grep/sed
    echo "                                                      Req'd  Req'd   Elap"
    echo "Job ID    Username Queue    Jobname    SessID NDS TSK Memory Time  S Time"
    echo "--------- -------- -------- ---------- ------ --- --- ------ ----- - -----"
    #Find and replace usernames
    qstat -a | grep -e "$2" \
    | sed 's/ft0805/Kratz /g' \
    | sed 's/fc1875/Hedi  /g' \
    | sed 's/ee4522/Andres/g' \
    | sed 's/fg3012/Alice /g' \
    | sed 's/fj9636/Tu    /g' \
    | sed 's/ej0271 /Sajeewa/g' \
    | sed 's/es4448/Pavel /g' \
    | sed 's/\.vpbs1//g'
    #Wait for 30 seconds before looping
    sleep 2.0
    for i in {1..15}
    do
      sleep 1.0
      read -t 1 -n 1 keypress
      if [[ "${keypress}" == *"q"* ]]; then
        echo ""
        exit
      fi
    done
  done
fi

echo ""
echo "Usage: Qtop -q [ queue name ]"
echo "Usage: Qtop -u [ username name ]"
echo ""
echo "Use -h for more help."
exit
